### ISSUE TITLE
How can install in the OMV5?

### ISSUE THREAD

**Issue by karmoybt** [OpenMediaVault-Plugin-Developers/openmediavault-wireguard#1] opened 2020-02-23 17:54 UTC
Hi (On the first, I'm a Noob )

I am trying to install Wp on my raspberry pi 3, but I don't know how to do it.
I have OMV 5.3.2-1,
I already installed OMV-Extra, but I can't find the plug-in (I think it opens VPN)

Need i install the wg without plugins?

Thanks you

**Comment by ryecoaaron** [comment] 2020-02-24 21:28
It is still very beta.  You would have to manually download the plugin and the wireguard packages from bintray - https://bintray.com/openmediavault-plugin-developers/usul-beta/

**Comment by karmoybt** [comment] 2020-02-27 08:43
Okey i will test

**Comment by isidoroi** [comment] 2020-04-27 16:10
I'm sorry, but it doesn't work. OMV5 - Usul 5.4.2.1 - Linux 5.4.0-0.bpo.4-amd64

**Comment by isidoroi** [comment] 2020-04-27 17:16
Log:
19:13
Failed to start WireGuard via wg-quick(8) for wgnet0.
systemd
19:13
wg-quick@wgnet0.service: Failed with result 'exit-code'.
systemd
19:13
wg-quick@wgnet0.service: Main process exited, code=exited, status=1/FAILURE
systemd
19:13
Cannot find device "wgnet0"
wg-quick
19:13
[#] ip link delete dev wgnet0
wg-quick
19:13
Unable to access interface: Protocol not supported
wg-quick
19:13
Error: Unknown device type.
wg-quick
19:13
[#] ip link add wgnet0 type wireguard
wg-quick
19:13
Starting WireGuard via wg-quick(8) for wgnet0...
systemd
19:13
Failed to start WireGuard via wg-quick(8) for wgnet0.
systemd

**Comment by ryecoaaron** [comment] 2020-04-27 17:36
I would guess the wireguard-dkms package failed to compile.  You would have seen this in the installation output.

**Comment by isidoroi** [comment] 2020-04-27 17:39
I loaded and installed the plugin. I haven't seen any messages of any kind

**Comment by isidoroi** [comment] 2020-04-27 17:47
when apply change and active plugin:
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run wireguard 2>&1' with exit code '1': debian: ---------- ID: configure_wireguard_wgnet0 Function: file.managed Name: /etc/wireguard/wgnet0.conf Result: True Comment: File /etc/wireguard/wgnet0.conf is in the correct state Started: 19:46:08.141938 Duration: 72.213 ms Changes: ---------- ID: configure_wireguard_client Function: file.managed Name: /etc/wireguard/wgnet_client.conf Result: True Comment: File /etc/wireguard/wgnet_client.conf is in the correct state Started: 19:46:08.214376 Duration: 9.79 ms Changes: ---------- ID: start_wireguard_service Function: service.running Name: wg-quick@wgnet0 Result: False Comment: Job for wg-quick@wgnet0.service failed because the control process exited with error code. See "systemctl status wg-quick@wgnet0.service" and "journalctl -xe" for details. Started: 19:46:08.240334 Duration: 171.701 ms Changes: Summary for debian ------------ Succeeded: 2 Failed: 1 ------------ Total states run: 3 Total run time: 253.704 ms

**Comment by ryecoaaron** [comment] 2020-04-27 17:53
If the wireguard-dkms package didn't install correctly (typically because of headers), doing anything in the plugin is pointless.  Usually it is caused by missing kernel headers.  And since this plugin is very beta as mentioned above, it should be installed from the command line so that important messages are seen.  That is why it is not in any user facing repo.

**Comment by TheLastProject** [comment] 2021-12-25 18:21
> It is still very beta. You would have to manually download the plugin and the wireguard packages from bintray - https://bintray.com/openmediavault-plugin-developers/usul-beta/

Any other place to install this on OMV5 now? Given bintray is no longer available.

**Comment by ryecoaaron** [comment] 2021-12-25 19:44
I haven't looked at it in a long time.  So, no idea if it still works.  https://omv-extras.org/testing/openmediavault-wireguard_5.0.2_all.deb

**Comment by TheLastProject** [comment] 2022-01-09 22:10
Sorry I haven't gotten back to you on this. I am still having trouble getting my Wireguard setup to behave exactly as I want it, but once I have it all working well and OMV6 is stable I may take a look at this project again :)

**Comment by ryecoaaron** [comment] 2022-10-04 15:48
Closing since OMV 5.x is EOL.

**Closed as completed by ryecoaaron** 2022-10-04 15:48 UTC
